---
abstract: 'Manipulate /etc/{passwd,shadow,group,gshadow} entries'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Passwd-Unix-Alt
requires:
  Crypt::PasswdMD5: 1.3
  Exporter: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  File::chdir: 0
  Struct::Compare: 0
  Test::More: 0.96
  perl: 5.010
resources:
  homepage: http://search.cpan.org/dist/Passwd-Unix-Alt/
  repository: http://github.com/sharyanto/perl-Passwd-Unix-Alt
version: 0.5201
